"""empty message

Revision ID: 58c27c301925
Revises: 11cf04736f96
Create Date: 2019-02-08 22:52:36.079287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c27c301925'
down_revision = '11cf04736f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('entityTypeId', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entityTypeId'], ['entity_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'entity_type', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_type', type_='unique')
    op.drop_table('entity')
    # ### end Alembic commands ###
