FROM python:3.5-alpine

RUN set -e; \
	apk add --no-cache --virtual .build-deps \
		gcc \
		libc-dev \
		linux-headers \
		postgresql-dev \
		python3-dev \
		musl-dev;

RUN mkdir /code
RUN mkdir /code/app
RUN mkdir /code/migrations
COPY app /code/app
COPY migrations /code/migrations
COPY requirements.txt code/requirements.txt

WORKDIR /code

RUN ls
RUN pip install -r requirements.txt
RUN pip install psycopg2
ENV FLASK_APP=app

CMD ["flask", "db", "upgrade"]